CREATE TABLE Employeroutput(
                        name varchar(300) NOT NULL,
                        id varchar(300) PRIMARY KEY NOT NULL,
                        basic_salary float NOT NULL, 
                        workdays int NOT NULL, 
                        sick_leave int NOT NULL, 
                        transportation_aid float NOT NULL,
                        dayshift_extra_hours int NOT NULL, 
                        nightshift_extra_hours int NOT NULL, 
                        dayshift_extra_hours_holidays int NOT NULL,
                        nightshift_extra_hours_holidays int NOT NULL, 
                        leave_days int NOT NULL, 
                        percentage_health_insurance float NOT NULL,
                        percentage_retirement_insurance float NOT NULL, 
                        percentage_retirement_fund float NOT NULL, 
                        devengado float NOT NULL,
                        deducido float NOT NULL,  
                        amounttopay float NOT NULL)